language: c++
before_script:
  - ./waf configure
  - ./waf build
script:
  - ./build/default/kuku
  - ./build/default/kuku -p

notifications:
  emails: tiisaishima@gmail.com
  on_success: always # default: change
  on_failure: always